// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import LogViewerController from "./log_viewer_controller"
application.register("log-viewer", LogViewerController)

import QuickContactController from "./quick_contact_controller"
application.register("quick-contact", QuickContactController)

import AiChatController from "./ai_chat_controller"
application.register("ai-chat", AiChatController)

import PrFilesController from "./pr_files_controller"
application.register("pr-files", PrFilesController)

import DeployFormController from "./deploy_form_controller"
application.register("deploy-form", DeployFormController)

import ConflictResolverController from "./conflict_resolver_controller"
application.register("conflict-resolver", ConflictResolverController)

import GherkinEditorController from "./gherkin_editor_controller"
application.register("gherkin-editor", GherkinEditorController)
